main: com.jaylawl.hellofucks.HelloFucks
name: HelloFucks
version: 0.1
author: jaylawl
description: Yes
commands:
  mycommand:
    description: An example command
    usage: /fuck
    permission: fuck.admin
    permission-message: You don't have the fuck permission.